apiVersion: v1
kind: Service
metadata:
  name: "demoxxx-service"
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  #type: LoadBalancer
  type: NodePort
  ports:
  # the port that this service should serve on
  - name: http
    port: 9080
  - name: https
    port: 9443

  selector:
    app: "demoxxx-selector"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "demoxxx-deployment"
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 1
  template:
    metadata:
      labels:
        app: "demoxxx-selector"
    spec:
      containers:
      - name: demoxxx
        image: demoxxx:latest
        readinessProbe:
          httpGet:
            path: /demoxxx/health
            port: 9080
          initialDelaySeconds: 20
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 100Mi
        env:
          - name: MB_KEYSTORE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mb-keystore-password
                key: password
          - name: MB_TRUSTSTORE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mb-truststore-password
                key: password
        volumeMounts:
          - name: keystores
            mountPath: /etc/wlp/config/keystore
            readOnly: true
          - name: truststores
            mountPath: /etc/wlp/config/truststore
            readOnly: true
          - name: liberty-config
            mountPath: /config/configDropins
      volumes:
        - name: keystores
          secret:
            secretName: mb-keystore
        - name: truststores
          secret:
            secretName: mb-truststore
        - name: liberty-config
          configMap:
            name: liberty-logging-config
            items:
              - key: keystore.xml
                path: defaults/keystore.xml
              - key: logging.xml
                path: defaults/logging.xml
